# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.session:
        class: Symfony\Component\HttpFoundation\Session\Session
        callMethod: 'Start'
    app.cart.adapter:
        class: ecommarg\cart\Cart\SessionAdapterInterface
        arguments: ['@app.session']
    app.cart:
        class: ecommarg\cart\Cart
        arguments: ['@app.cart.adapter']
    
    #app.cart:
    #    class: ecommarg\cart\Cart
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
